"use client";
import { Eye } from "lucide-react";
import { ListItem, ListItemAction, ListItemDescreption } from "./ui/list-item";
import { Button } from "./ui/button";
import { endpoint_colors, EndpointMethod } from "@/constants";
import React from "react";
import {
  Collapsible,
  CollapsibleContent,
  CollapsibleTrigger,
} from "@radix-ui/react-collapsible";
import EndpointExampleDrawer from "./EndpointExampleDrawer";

interface Props {
  endpoint: {
    url: string;
    method: keyof typeof EndpointMethod;
  };
}
const Endpoint = ({ endpoint }: Props) => {
  const [isOpen, setIsOpen] = React.useState(false);

  return (
    <Collapsible
      open={isOpen}
      onOpenChange={setIsOpen}
      className="my-2 bg-muted/40 "
    >
      <ListItem className="flex items-center gap-5 flex-wrap">
        <ListItemDescreption className="flex flex-row  items-center justify-start gap-4  ">
          <div
            className="text-white text-sm w-fit p-2 px-4 min-w-20 rounded-lg "
            style={{ background: endpoint_colors[endpoint.method] }}
          >
            <p className="text-center">{endpoint.method}</p>
          </div>
          <h4 className="text-sm">{endpoint.url}</h4>
        </ListItemDescreption>

        <section className="flex items-center gap-5">
          <EndpointExampleDrawer></EndpointExampleDrawer>
          <Button className="cursor-pointer" variant={"outline"} asChild>
            <CollapsibleTrigger asChild>
              <ListItemAction>
                <p className="text-sm">Details</p>
                <Eye />
              </ListItemAction>
            </CollapsibleTrigger>
          </Button>
        </section>
      </ListItem>

      <CollapsibleContent className="flex flex-col gap-2 p-5">
        <p>
          Here all content of this enpoint will be listed , from description
          generated by LLM to parameters to ..
        </p>
      </CollapsibleContent>
    </Collapsible>
  );
};

export default React.memo(Endpoint);
